{"name":"Local: exception","url":"k:\\Phitron\\SDT\\Python\\Module-03\\exception.py","tests":[{"id":1732994906933,"input":"","output":""}],"interactive":false,"memoryLimit":1024,"timeLimit":3000,"srcPath":"k:\\Phitron\\SDT\\Python\\Module-03\\exception.py","group":"local","local":true}